// <auto-generated />
using System;
using FA.JustBlog.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FA.JustBlog.Entity.Migrations
{
    [DbContext(typeof(JustBlogContext))]
    [Migration("20221004160027_first-init")]
    partial class firstinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is category 1",
                            Name = "Category 1",
                            UrlSlug = "category_1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is category 2",
                            Name = "Category 2",
                            UrlSlug = "category_2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is category 3",
                            Name = "Category 3",
                            UrlSlug = "category_3"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommentHeader")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CommentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 10, 4, 23, 0, 26, 989, DateTimeKind.Local).AddTicks(6247));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentHeader = "Header 1",
                            CommentText = "Text 1",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abc@gmail.com",
                            Name = "Comment 1",
                            PostId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentHeader = "Header 2",
                            CommentText = "Text 2",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abcd@gmail.com",
                            Name = "Comment 2",
                            PostId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentHeader = "Header 3",
                            CommentText = "Text 3",
                            CommentTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abce@gmail.com",
                            Name = "Comment 3",
                            PostId = 3
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Modified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PostedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2022, 10, 4, 23, 0, 26, 989, DateTimeKind.Local).AddTicks(8567));

                    b.Property<bool>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RateCount")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalRate")
                        .HasColumnType("int");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Post", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Modified = false,
                            PostContent = "PostContent 1",
                            PostedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            RateCount = 2,
                            ShortDescription = "ShortDescription 1",
                            Title = "Title 1",
                            TotalRate = 2,
                            UrlSlug = "post_slug_1",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Modified = false,
                            PostContent = "PostContent 2",
                            PostedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            RateCount = 3,
                            ShortDescription = "ShortDescription 2",
                            Title = "Title 2",
                            TotalRate = 3,
                            UrlSlug = "post_slug_2",
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Modified = false,
                            PostContent = "PostContent 3",
                            PostedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = false,
                            RateCount = 1,
                            ShortDescription = "ShortDescription 3",
                            Title = "Title 3",
                            TotalRate = 1,
                            UrlSlug = "post_slug_3",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.PostTagMap", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PostTagMap", (string)null);

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            PostId = 1
                        },
                        new
                        {
                            TagId = 2,
                            PostId = 2
                        },
                        new
                        {
                            TagId = 3,
                            PostId = 3
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            Description = "This is tag 1",
                            Name = "Tag 1",
                            UrlSlug = "tags_1"
                        },
                        new
                        {
                            Id = 2,
                            Count = 2,
                            Description = "This is tag 2",
                            Name = "Tag 2",
                            UrlSlug = "tags_2"
                        },
                        new
                        {
                            Id = 3,
                            Count = 3,
                            Description = "This is tag 3",
                            Name = "Tag 2",
                            UrlSlug = "tags_3"
                        });
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Comment", b =>
                {
                    b.HasOne("FA.JustBlog.Entity.Entity.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Comment_Post");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Post", b =>
                {
                    b.HasOne("FA.JustBlog.Entity.Entity.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Category_Post");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.PostTagMap", b =>
                {
                    b.HasOne("FA.JustBlog.Entity.Entity.Post", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Post_PostTagMap");

                    b.HasOne("FA.JustBlog.Entity.Entity.Tag", "Tags")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Tags_PostTagMap");

                    b.Navigation("Post");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("FA.JustBlog.Entity.Entity.Tag", b =>
                {
                    b.Navigation("PostTagMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
